Feature/#56 user survey
racketometer/thesis pull request #86
Opened 2016-09-27 10:30 UTC by Crevil

closes #56 
Fixes corrections from review 3 as well.

2016-09-29 09:18 UTC, Karnich requested changes

2016-09-29 09:18 UTC, Karnich commented on files/userSurvey.tex
> +This is approved by 36\% of the users, why this is a viable solution for the prototype.
make it more clear that 36 % are people who are willing to buy a new racket with the sensor build in

2016-10-02 10:22 UTC, Crevil commented on files/userSurvey.tex
> +This is approved by 36\% of the users, why this is a viable solution for the prototype.
I've rephrased this part. Better?

2016-10-03 12:00 UTC, Karnich approved these changes

2016-10-03 12:00 UTC, Karnich commented
its goood! does have a conflict tho

2016-10-04 11:39 UTC, merged